# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Blog MedSur
email: asesoriamedsur@gmail.com
description: >
  Últimas novedades de MedSur. Actualizaremos esta página con datos interesantes y recetas para nuestros pacientes.
logo: "/assets/images/logo.jpg"
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://blog.medsur.cl" # the base hostname & protocol for your site
paginate:	15 # The number of posts to show per page on your homepage

name: 'Natalia Tasso'
bio: >
  Nutricionista
  MedSur Puerto Varas
author_image: "/assets/images/autor.png"
# twitter_username: jekyllrb
github_username:  newtri

# Google Analytics
analytics_id: "UA-60759619-6"

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
